export default function CartPanel({ cart, onChangeQuantity, onRemove, onClear, onCheckout, onCheckoutOptions, checkoutOptions, onClose, pending, error }) {
  const items = cart?.items || []
  const summary = cart?.summary || cart || {}
  const money = (value) => `$${Number(value || 0).toFixed(2)}`
  return <aside className="cart-panel" aria-label="Your order">
    <div className="cart-panel-header"><div><span className="eyebrow">Your basket</span><h2>Ready when you are</h2></div><button className="close-button" type="button" onClick={onClose} aria-label="Close cart">×</button></div>
    {error && <p className="form-error" role="alert">{error}</p>}
    {!items.length ? <div className="empty-cart"><span>🛍️</span><p>Your basket is waiting for something delicious.</p></div> : <>
      <div className="cart-items">{items.map((item) => { const id = item.id ?? item.cart_item_id; const menuItem = item.menu_item || item.menuItem || item; return <div className="cart-item" key={id}><span className="cart-emoji">{menuItem.emoji || '🍽️'}</span><div><strong>{menuItem.name || 'Menu item'}</strong><small>{money(item.line_total ?? item.total ?? Number(menuItem.price) * item.quantity)}</small><div className="quantity"><button type="button" disabled={pending} onClick={() => item.quantity > 1 ? onChangeQuantity(id, item.quantity - 1) : onRemove(id)} aria-label={`Remove one ${menuItem.name || 'item'}`}>−</button><span>{item.quantity}</span><button type="button" disabled={pending} onClick={() => onChangeQuantity(id, item.quantity + 1)} aria-label={`Add one ${menuItem.name || 'item'}`}>+</button></div></div></div> })}</div>
      <div className="bill"><div><span>Subtotal</span><span>{money(summary.subtotal)}</span></div><div><span>Delivery</span><span>{money(summary.deliveryFee ?? summary.delivery_fee)}</span></div><div><span>Tax</span><span>{money(summary.tax)}</span></div><div className="total"><strong>Total</strong><strong>{money(summary.total)}</strong></div></div>
      {checkoutOptions && <div className="checkout-options"><label>Fulfillment<select value={checkoutOptions.type} onChange={(event) => onCheckoutOptions({ ...checkoutOptions, type: event.target.value })}><option value="DELIVERY">Delivery</option><option value="PICKUP" disabled={!checkoutOptions.points.length}>Pickup</option></select></label>{checkoutOptions.type === 'DELIVERY' ? <><label>Address<select value={checkoutOptions.address_id} onChange={(event) => onCheckoutOptions({ ...checkoutOptions, address_id: event.target.value })}>{(checkoutOptions.addresses || []).map((address) => <option key={address.id} value={address.id}>{address.label || address.address_line}</option>)}</select></label>{checkoutOptions.windows.length > 0 && <label>Delivery window<select value={checkoutOptions.delivery_window_id} onChange={(event) => onCheckoutOptions({ ...checkoutOptions, delivery_window_id: event.target.value })}>{checkoutOptions.windows.map((window) => <option key={window.id} value={window.id}>{window.label} ({window.starts_at}–{window.ends_at})</option>)}</select></label>}</> : <label>Pickup point<select value={checkoutOptions.pickup_point_id} onChange={(event) => onCheckoutOptions({ ...checkoutOptions, pickup_point_id: event.target.value })}>{checkoutOptions.points.map((point) => <option key={point.id} value={point.id}>{point.name} · {point.address}</option>)}</select></label>}</div>}
      <button className="checkout-button" type="button" disabled={pending || (checkoutOptions?.type === 'PICKUP' && !checkoutOptions.pickup_point_id)} onClick={onCheckout}>{checkoutOptions ? 'Place order' : 'Continue to checkout'} <span>→</span></button><button className="text-button" type="button" disabled={pending} onClick={onClear}>Clear basket</button>
    </>}
  </aside>
}
